### ISSUE TITLE
where is urlencode

### ISSUE THREAD

**Issue by kevin991** [glmck13/QBOnlineScripts#1]
The scripts need urlencode, where is it?

**Comment by glmck13** [comment]
There's a package in the Debian/Ubuntu releases named 
"gridsite-clients", which includes a version of urlencode.

**Comment by kevin991** [comment]
OK thanks for the tip on the gridsite-clients. That fixed the urlencode.

After a bit of playing around, I managed to get the token, did the intuit URL to get the OAUTH_VERIFIER which created the oauth_verifier file. But now I get a curl error saying that the signature is invalid. Any ideas?
Here is the curl line + error message:

curl -s 'https://oauth.intuit.com/oauth/v1/get_access_token?oauth_consumer_key=qyprdLNOzVPIQXTbRXu1Eh2I5cPvkf&oauth_nonce=hUYKQXzj17XKzLrJVovs5OZrHf5Z&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1467383223&oauth_token=qyprdhRIROyvqz24rNMgiHZkE6Wins5gvnp3ou2ww3YS0NiL&oauth_verifier=ccwi3d3&oauth_version=1.0&oauth_signature=o8cp7SxL2k263aZJ9TbRrUtrp9o%3D'

oauth_problem=signature_invalid
- I noticed that the signature is urlencoded, should it be?

Thanks,
Kevin.

**Comment by glmck13** [comment]
Kevin - I just noticed your post above.   I'm assuming the curl command is what was generated within "accToken.sh".  I've run the (reqToken.sh, accToken.sh) sequence successfully many times, and never encountered a "signature_invalid" error. :-(

---

Kevin - Before running accToken.sh, "dot" qboTokens.conf and check that 
the OAUTH variables have been set correctly.  OAUTH_TOKEN & 
OAUTH_TOKEN_SECRET should be the values returned by reqToken.sh, while 
OAUTH_VERIFIER should be the value returned in callback.cgi:
$ . ./qboTokens.conf
$ set | grep OAUTH
OAUTH_ACCURL=https://oauth.intuit.com/oauth/v1/get_access_token
OAUTH_CALLBACK=oauth_callback=http%3A%2F%2Flocalhost%2Foauth%2Fcallback.cgi
OAUTH_CONSUMER_KEY=oauth_consumer_key=...
OAUTH_CONSUMER_SECRET=oauth_consumer_secret=...
OAUTH_LOGIN=https://appcenter.intuit.com/Connect/Begin
OAUTH_NONCE=oauth_nonce=SvMcCFuDTSUyhaAMZtP45jMWiJSFEpP
OAUTH_REQURL=https://oauth.intuit.com/oauth/v1/get_request_token
OAUTH_SIGNATURE_METHOD=oauth_signature_method=HMAC-SHA1
OAUTH_TIMESTAMP=oauth_timestamp=1467481086
OAUTH_TOKEN=oauth_token=...
OAUTH_TOKEN_SECRET=oauth_token_secret=...
OAUTH_VERIFIER=oauth_verifier=...
OAUTH_VERSION=oauth_version=1.0
